### PR TITLE
v2

### LINKED ISSUE #2: Paths of properties of an object with index signature gets truncated.
See title.
If we have a object inside a object with an index signature, all paths of the nested objects are getting truncated.

Example:
```ts
type TestType = {
    [index: string]: {
        a: string
        b: number
    }
}

// should be string | number | `${string}.a` | `${string}.b`
// but is string | number
type Paths = Path<TestType>
```

Typescript simplifies unions of string and template literals to only string, which truncates the template literals.
There are ways to fix this (using `(string & {})` instead of just `string`) but these would damage readability of code auto completion or error messages.

### LINKED ISSUE #3: setByPath shows Paths to readonly properties
`setByPath()` uses the `Path` type, which does not differ between readonly and writeable properties. So the auto completion contains paths to properties, which are readonly.

We should create an extra type for `setByPath` similiar to `Path` which only returns paths to writeable properties.

### LINKED ISSUE #4: Enhance typing of PathValue for unions.
Let's consider the following cases:

```typescript
type TestType = {
  a: number | { nested: string }
}

type value = PathValue<TestType, 'a.nested'> // is string
```
Here, the type of `value` should be `undefined | string`, since we cannot determine if `a` is a `number` or not.

In this case:
```typescript
type TestType = {
  a: string | { nested: string }
}

type value = PathValue<TestType, 'a.nested'>  // is string
```

`string` is the correct type, as we can access individual characters of a string using index notation.

It might be necessary to split the PathValue type into two distinct types, one for getByPath and another for setByPath, as suggested in this issue: https://github.com/clickbar/dot-diver/issues/3. Additionally, we may need to exclude paths of objects in unions from setByPath, since we cannot determine at runtime whether it is an object or a primitive.

### LINKED ISSUE #5: Use circular constraints for depth-problem
Currently, if a type has many cyclic dependencies (see [readme-question](https://github.com/clickbar/dot-diver#-i-get-the-error-type-instantiation-is-excessively-deep-and-possibly-infinitets2589)), TypeScript fails due to the large number of possible paths.

If circular constraints were better supported (see https://github.com/microsoft/TypeScript/issues/51011), an alternative approach like the one below could be feasible:

```typescript
function getByPath<T extends SearchableObject, P extends PathsOneLevelDeeper<T, P>>(
  object: T,
  path: P
): number {
  const pathArray = (path as string).split('.')

  return pathArray.reduce((accumulator: any, current) => accumulator?.[current], object) as any
}
```

The `PathsOneLevel` type would  return `P` (or a valid path in `T` close to `P`)  and all paths on level deeper. This would significantly reduce the number of paths TypeScript has to compute, potentially addressing the issue with excessive recursion depth.

### LINKED ISSUE #30: Does not handle empty string correctly
```js
const fields = { foo: 'bar' };
console.log(getByPath(fields, '')); // undefined

setByPath(fields, '', 'baz');
console.log(fields); // { "": "baz", foo: "bar" }
```

Expected
```js
const fields = { foo: 'bar' };
console.log(getByPath(fields, '')); // { foo: 'bar' }

setByPath(fields, '', 'baz'); // Throw exception path is empty
```

### LINKED ISSUE #34: HasOwnProperty check causes reactivity issues
Here is a demo

https://play.vuejs.org/#eNp9VU1v20YQ/StjXkghLOUmPRSJlMIpckgPtdEavZhGwFBDaW1yl9hdSjYU/fe+2aVkxjaii5bz8ea9mVlyn1z0fbEdOHmfLFxtVe/JsR/6j6VWXW+spz1Zrmqvtpzj1ORUm64fPK/oQI01HaVIT0td6mbQiDNaEP6r2oEv/FXlN5n5dpdTj1NOWzHPaI9wP5/Tl4b8hoOPVoadTj3gta+UpgoWn4tf046prjTdDS7QC0kBqhAg1VB2JhiF0nU7rNhlaZHOxjKlR/0bcd/SMmZFs4VOC9qlPwj7QOgSyHanHLSipmao9IZc36pYNDBVWmy87lh7R5Ve0a5q70F3pyVohEJVrpFlmWnQXrWC2ChEC5BV642nvq1qDhVeiEIbgtixyjKULgKToE5iWmRpdpjFZSy2lKriaYylTNwKtvMP+FucsIqW9RoyfqFf4Xjz5tSnWPKeH5FzDL5Rt9H5rM708QYp0tuXtu/faS/NDR3+AeLmVOAVWreTSYXZRGZsrbHSCqxhtj+gBdEOsV2wxjXNIIfGYOTPPggCGnytOjaDz7IZLT+KZnq+qDGnCJVzSntrGtVy0Sjr/FdddZzCeg0VqYAecnp7fn4e8Sfbv2b/6THgSYm4BrkcwxUodeg3yZ6Du9gurK2k55k8zH6cMQLjnj5FFpZXQ81ZVg/WonPxbl1V1j8JI5JLEU9E/rFn09AYT2fLJaWRV4oRHaOO7iXcemjbiessDq1AR7wRtGJTucudvrKmZ+sfi7pq21f4xPxRsPxGLYNeMa4Cr6I9zHjiHoHCpRUcrCCC8rGXQH2+FG/RveNraZyvLEUxDnQc5B+TSZ6WJ4S8TH8a4gTo9Z2YhTkt5vH1iRcnHjx3uNue8US0WKltOBBpgFXtRV2zc+9pv4/sD4fFNztGnAqf3AeoBcg8oizmE+wkT7yDjkatiztnNN7iodVlInLA0172spOuTAAXC5QJZmV2fwWbt9j0o73ecH3/iv3OPYitTK4sO7ZbLpOTz1cWjKP7879/8wPOJ2dnVkOL6J84/2Fn2kE4xrBPWA3QnsQFtl/Ct0jp9bX7/OBZu6MoIRq3I+rGt+jPn0h/ovuu+C3kYZnQxa9btoKJBsJRvPs9OfwPJ2xysQ==

The issue is because of the hasOwnProperty check coming from the global Object prototype and not the Proxy one, the path which doesn't yet exist is never actually called on the proxy, which means vue has no way to track it

Replacing with `!current.hasOwnProperty(pathPart)` fixes the reactivity issue without introducing the vulnerability this code fixes

Thought?

### PR DESCRIPTION
**Pull request by djfhe**
fix https://github.com/clickbar/dot-diver/issues/3
fix https://github.com/clickbar/dot-diver/issues/4
fix https://github.com/clickbar/dot-diver/issues/5
fix https://github.com/clickbar/dot-diver/issues/30
fix #34
Partially fixes https://github.com/clickbar/dot-diver/issues/2

We use the currently given path (typed by the user) as an offset to only show the next 3 level deep properties. This improves performance and removes the need for a custom implementation (except the user wants to see deeper by default).
We now also handle read only and union properties correctly.

### CODE REVIEW

**Comment by djfhe** [comment]
Still wip but pretty far.
Resolve https://github.com/clickbar/dot-diver/issues/5 by taking advantage of circular references using a tuple trick.

Still want to solve:
- https://github.com/clickbar/dot-diver/issues/3
- https://github.com/clickbar/dot-diver/issues/2
- https://github.com/clickbar/dot-diver/issues/4

before merging this into main.
This should be v2 then since we break backwards compatibility by changing the `Path` type and custom implementations.

Unsure if i can solve
https://github.com/clickbar/dot-diver/issues/1
but i don't think this will really be necessary anymore, since we now support nearly max depth while also showing a sane number of path (currently the next two levels).

**Comment by djfhe** [comment]
i think i fixed
https://github.com/clickbar/dot-diver/issues/3
and
https://github.com/clickbar/dot-diver/issues/4

i still have to look a bit more into https://github.com/clickbar/dot-diver/issues/2.
Additional runtime checks are also required to check if the typescript behavior is the same as the javascript one.

I would like to also add some performance checks/tests to find potential regressions and/or problems.

**Comment by djfhe** [comment]
@saibotk u can already take a look if you want.
But otherwise, it should be pretty much be ready.

File: src/index.ts [hunk 1]
```diff
@@ -75,36 +83,44 @@ type IsPrimitive<T> = T extends string | number | boolean | bigint | symbol | un
 // remove null and undefined from a type
 type ExcludeNullUndefined<T> = Exclude<T, null | undefined>
 
+// check if a type is an empty array
+type IsEmptyArray<T> = T extends readonly [] ? true : false
+
 // check if a type is a tuple
-type IsTuple<T> = T extends [any, ...any[]] ? true : false
+type IsTuple<T> = T extends readonly [any, ...any[]] ? true : false
```
Comment (saibotk) [inline src/index.ts]: maybe use unknown here too?

https://github.com/sindresorhus/type-fest/blob/2967fe62b55c7cc13fa003259e119f98edeb9c28/source/internal/array.d.ts#L13

File: src/index.ts [hunk 2]
```diff
@@ -75,36 +83,44 @@ type IsPrimitive<T> = T extends string | number | boolean | bigint | symbol | un
...
 type Writeable<T> = {
   -readonly [K in keyof T]: T[K]
 }
 
+// remove readonly properties
+type RemoveReadonlyProperties<T> = {
+  [K in keyof T as IsEqual<{ [k in K]: T[K] }, { readonly [k in K]: T[K] }> extends true
+    ? never
+    : K]: T[K]
+}
```
Comment (saibotk) [inline src/index.ts]: Maybe use https://github.com/sindresorhus/type-fest/blob/2967fe62b55c7cc13fa003259e119f98edeb9c28/source/writable-keys-of.d.ts#L28

File: src/index.ts [hunk 3]
```diff
@@ -75,36 +83,44 @@ type IsPrimitive<T> = T extends string | number | boolean | bigint | symbol | un
...
+
+type BeforeLast<T extends string, V extends string | number> = T extends string
```
Comment (saibotk) [inline src/index.ts:104]: Add a comment and maybe rename this type

File: src/index.ts [hunk 4]
```diff
@@ -116,143 +118,325 @@ type BuildTuple<L extends number, T extends unknown[] = []> = T extends {
...
+
+/* -------------------------------------------------------------------------- */
+/*                                    Path                                    */
+/* -------------------------------------------------------------------------- */
+
+/**
+ * Similar to SimplePath, PathWithOffset return all paths in the given type and returns them until it reaches its max depth.
+ *
+ * The difference is that PathWithOffset allows to specify an offset to start the traversal from. It will start the traversal
+ * by the last parent in the given offset.
```
Comment (saibotk) [inline src/index.ts]:
```suggestion
 * from the last parent at the given offset.
```

File: src/index.ts [hunk 5]
```diff
@@ -116,143 +118,325 @@ type BuildTuple<L extends number, T extends unknown[] = []> = T extends {
...
-      ? PathStep<Writeable<ExcludeNullUndefined<T>>, MinusOne<DepthCarry>>
-      : never
+/**
+ *
+ * CircularConstraintPathHelper allows us to use Path as a cyclic constraint for a generic parameter. e.g.
+ * function foo<T, P extends CircularConstraintPathHelper<T, 3, [P]>>(...)
+ *
+ * This allows us to use the given path as the offset parameter for the path type.
+ *
+ * TODO: Find out why this works and if it may break in the future.
```
Comment (saibotk) [inline src/index.ts]: still relevant?

File: src/index.ts [hunk 6]
```diff
@@ -116,143 +118,325 @@ type BuildTuple<L extends number, T extends unknown[] = []> = T extends {
...
+  ? SimplePath<T, Config>
+  : P[number] extends infer PV
+    ? PV extends string | number
+      ? PathWithOffset<T, Config, PV>
+      : SimplePath<T, Config>
+    : SimplePath<T, Config>
 
-type PathEntry<T, Depth extends number = 10> = Path<T, BuildTuple<Depth>>
+/**
+ * Path return all paths in the given type and returns them until it reaches its max depth.
```
Comment (saibotk) [inline src/index.ts]:
```suggestion
 * Path returns all paths in the given type and returns them until it reaches its max depth.
```

File: src/index.ts [hunk 7]
```diff
@@ -116,143 +118,325 @@ type BuildTuple<L extends number, T extends unknown[] = []> = T extends {
...
+  }, object) as PathValue<T, P>
 }
 
 function throwAssignmentError(current: unknown, path: string): never {
   const type = current === null ? 'null' : typeof current
   throw new TypeError(`Cannot create property '${path}' on ${type}`)
 }
 
+type SetPathValue<T, P extends string | number> = PathValue<T, P>
+
```
Comment (saibotk) [inline src/index.ts]: can be removed

File: test/index.test-d.ts [hunk 8]
```diff
@@ -665,12 +675,266 @@ it('Test readme usage example: 🔄 Objects with cyclic dependency', () => {
...
+    | `e.${number}`
+    | `e.${number}.f`
+    | `e.${number}.f.${any}`
+    | number
+    | `${number}`
+
+  expectTypeOf<Path<TestType>>().toEqualTypeOf<ExpectedPaths>
+})
+
+it('Adds undefined if it is uncertain if the property exists', () => {
```
Comment (saibotk) [inline test/index.test-d.ts]:
```suggestion
it('Adds undefined if it is uncertain if the property exists in a union', () => {
```

File: test/index.test-d.ts [hunk 9]
```diff
@@ -665,12 +675,266 @@ it('Test readme usage example: 🔄 Objects with cyclic dependency', () => {
...
+  expectTypeOf<PathValue<TestType, 'e.0.f.g'>>().toEqualTypeOf<string | undefined>()
+  expectTypeOf<PathValue<TestType, 'e.1.f.g'>>().toEqualTypeOf<string | undefined>()
+
+  expectTypeOf<PathValue<TestType, number>>().toEqualTypeOf<number | (() => void) | undefined>()
+  expectTypeOf<PathValue<TestType, `${number}`>>().toEqualTypeOf<
+    number | (() => void) | undefined
+  >()
+})
+
+it('Does not need to add undefined if it is certain that the property exists', () => {
```
Comment (saibotk) [inline test/index.test-d.ts]:
```suggestion
it('Does not add undefined if it is certain that the property exists on unions', () => {
```

File: test/index.test-d.ts [hunk 10]
```diff
@@ -665,12 +675,266 @@ it('Test readme usage example: 🔄 Objects with cyclic dependency', () => {
...
+  type ExpectedValue2 = ExpectedValue | boolean | undefined
+
+  expectTypeOf<PathValue<TestType2, 'a'>>().toEqualTypeOf<ExpectedValue2>()
+})
+
+/**
+ * We added onlyWriteable to the config to allow only writeable properties to be set.
+ * @see https://github.com/clickbar/dot-diver/issues/3
+ */
+test('Readonly config works with Path', () => {
```
Comment (saibotk) [inline test/index.test-d.ts]:
```suggestion
test('Writable config works with Path', () => {
```

**Review by saibotk — CHANGES_REQUESTED** [review]

File: README.md [hunk 11]
```diff
@@ -175,7 +175,7 @@ type ValueAtPathChildren_0_Label = PathValue<Node, 'children.0.label', 3> // Out
 type ValueAtPathParent_Parent_Parent = PathValue<Node, 'parent.parent.parent.parent', 3> // Output: unknown (due to the depth limit)
 ```
 
-The default depth is currently **10**.\
+The default depth is currently **3**.\
 At the moment, it is not possible to customize it when using the provided `getByPath` and `setByPath` functions.
 This is further explained in this [issue](https://github.com/clickbar/dot-diver/issues/1).
```
Comment (saibotk) [inline README.md]: explain that this is only relative to the current offset.

**Review by saibotk — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 12]
```diff
@@ -2,7 +2,113 @@
 
 All notable changes to **dot-diver** will be documented here. Inspired by [keep a changelog](https://keepachangelog.com/en/1.0.0/)
 
-## Unreleased
+## [2.0.0](https://github.com/clickbar/dot-diver/tree/2.0.0) (2024-03-25)
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
## [2.0.0](https://github.com/clickbar/dot-diver/tree/2.0.0) (2024-08-18)
```

File: CHANGELOG.md [hunk 13]
```diff
@@ -2,7 +2,113 @@
...
+
+## features
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
## Features
```

File: CHANGELOG.md [hunk 14]
```diff
@@ -2,7 +2,113 @@
...
+
+Support Paths up to a depth of 40 (limited by TypeScript's recursion depth) by cyclic constraints to only lookup up
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
Support paths up to a depth of 40 (limited by TypeScript's recursion depth) by utilizing cyclic constraints to only lookup up
```

File: CHANGELOG.md [hunk 15]
```diff
@@ -2,7 +2,113 @@
...
+the next 3 (default) levels. The limit of 40 comes by accessing the value at this depth level. This should
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
the next 3 (default) levels. This should
```

File: CHANGELOG.md [hunk 16]
```diff
@@ -2,7 +2,113 @@
...
+- partially fixes <https://github.com/clickbar/dot-diver/issues/2>
+- <https://github.com/clickbar/dot-diver/issues/3>
+- <https://github.com/clickbar/dot-diver/issues/4>
+- <https://github.com/clickbar/dot-diver/issues/5>
+- <https://github.com/clickbar/dot-diver/issues/30>
+- <https://github.com/clickbar/dot-diver/issues/34>
+
+### Breaking Changes
+
+In general the `depth` limit of Path is no long the max depth, but instead a 'lookahead' depth. E.g. if you have a depth limit of 3,
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
In general the `depth` limit of `Path` is no longer the max depth, but instead a 'lookahead' depth. E.g. if you have a depth limit of 3,
```

File: CHANGELOG.md [hunk 17]
```diff
@@ -2,7 +2,113 @@
...
+and are currently (while typing) at a depth of 2, the paths for the next 3 levels will be shown in autocompletion. You can no longer
+constraint the max depth of the path, but only the lookahead depth. If this is a problem for you, please open a issue.
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
constrain the max depth of the path, but only the lookahead depth. If this is a problem for you, please open an issue.
```

File: CHANGELOG.md [hunk 18]
```diff
@@ -2,7 +2,113 @@
...
+
+#### Value of Array Member, Optional Properties and Union Types
+
+In 1.0.0 you got the full type of nested unions.
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
In 1.0.0 you received the full type for nested unions.
```

File: CHANGELOG.md [hunk 19]
```diff
@@ -2,7 +2,113 @@
...
+
+```typescript
+type A = { a: number | { nested: string } }
+
+type NestedType = PathValue<A, 'a.nested'> // string
+```
+
+This is incorrect behavior, as `a` could be a number and not an object with a `nested` property. This is now fixed.
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
This is incorrect behavior, because `a` could also be a number and not an object with a `nested` property. This is now fixed.
```

File: CHANGELOG.md [hunk 20]
```diff
@@ -2,7 +2,113 @@
...
+
+```PathValue``` got now splitted into two different types:
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
```PathValue``` was split into two different types:
```

File: CHANGELOG.md [hunk 21]
```diff
@@ -2,7 +2,113 @@
...
+
+- ```GetPathValue``` for reading values
+- ```SetPathValue``` for setting values
+
+these behave different when accessing values in a object.
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
the resulting types differ when accessing values in an object or setting them.
```

File: CHANGELOG.md [hunk 22]
```diff
@@ -2,7 +2,113 @@
...
+type NestedType3 = GetPathValue<A, 'c.5'> // string | undefined
+type NestedType4 = GetPathValue<A, 'd.nested'> // string | undefined
+
+type NestedType5 = SetPathValue<A, 'a.nested', string> // string
+type NestedType6 = SetPathValue<A, 'b.key', number> // number
+type NestedType7 = SetPathValue<A, 'c.5', string> // string
+type NestedType8 = SetPathValue<A, 'd.nested', string> // string
+```
+
+These type are used by there respective functions `getByPath` and `setByPath` and should more accurately represent the types of accessed values but can break old code.
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
These type are used by their respective functions `getByPath` and `setByPath` and should more accurately represent the types of accessed values but can potentially break old code.
```

File: CHANGELOG.md [hunk 23]
```diff
@@ -2,7 +2,113 @@
...
+
+#### Custom Implementation
+
+Implementation of custom `getByPath` and `setByPath` functions need to be updated for the new types.
+If you implemented them to change the depth limit you might not need them anymore, as the (max) depth is now 40. (limited by access to the path value at that depth)
```
Comment (saibotk) [inline CHANGELOG.md]:
```suggestion
If you implemented them to change the depth limit you might not need them anymore, as the (max) depth is now 40 (limited by TypeScript's recursion limit).
```

**Review by saibotk — CHANGES_REQUESTED** [review]

**Review by saibotk — APPROVED** [review]
Let's shippppp
